((nil . ((fill-column . 100)
         (indent-tabs-mode . nil)))
 (c-mode . ((c-file-style . "GNU")
            (c-basic-offset . 2)
            (c-file-offsets
             (brace-list-intro . +))
            ))
 (c-ts-mode . ((c-ts-mode-indent-offset . 2)
               (c-ts-mode-style . gnu)
               ))
 (css-mode . ((css-indent-offset . 2)
              ))
 (web-mode . ((web-mode-markup-indent-offset . 2)
              (web-mode-css-indent-offset . 2)
              (web-mode-code-indent-offset . 2)
              ))
 )
